### ISSUE TITLE
extended_entities is not adressed in rest search client

### ISSUE THREAD

**Issue by MyraBaba** [DanielaSfregola/twitter4s#101]
tweet_mode=extended   gives more media (extra jpg, gifs and video)
Most of the media coming from entended_entites. 
search rest API should be fixed accordingly.

`"extended_entities":  {
          "media":  [
             {
              "id": 824577120492015600,
              "id_str": "824577120492015616",
              "indices":  [
                63,
                86
              ],
              "media_url": "http://pbs.twimg.com/media/C3F8hbTXUAAym4i.jpg",
              "media_url_https": "https://pbs.twimg.com/media/C3F8hbTXUAAym4i.jpg",
              "url": "https://t.co/GzxWYyPuMy",
              "display_url": "pic.twitter.com/GzxWYyPuMy",
              "expanded_url": "https://twitter.com/yeniakit/status/824577122358427648/photo/1",
              "type": "photo",
              "sizes":  {
                "large":  {
                  "w": 625,
                  "h": 313,
                  "resize": "fit"
                },
                "small":  {
                  "w": 625,
                  "h": 313,
                  "resize": "fit"
                },
                "medium":  {
                  "w": 625,
                  "h": 313,
                  "resize": "fit"
                },
                "thumb":  {
                  "w": 150,
                  "h": 150,
                  "resize": "crop"
                }
              }
            }
          ]
        },`

**Comment by DanielaSfregola** [comment]
@MyraBaba please try to be more explicit when raising tickets.

Which version of twitter4s are you using? When you state that `search rest API should be fixed accordingly` what do you mean? Do you mean that `extended_entities` should be added in the tweet entity? do you mean that there is a parameter that we should support?

**Comment by MyraBaba** [comment]
when I used tweet_mode = extended   it looks like response JSON couldnt parse correctly.  I am trying to debug and fix like : 

to add: 

entities.Tweet.scala
extended_entities: Option[ExtendedEntities] = None,


and:

case class ExtendedEntities(media: Seq[ExtendenEntitiesMediaDetails] = Seq.empty)

case class ExtendenEntitiesMediaDetails(display_url: String ,
                                expanded_url: String ,
                                id_str: String ,
                                media_url: String ,
                                `type`: String,
                                url: String)
but coulndt succeded

..

yes I mean extenden_entities should be added Tweet.entity.


if you direct me I try to fix.

**Comment by DanielaSfregola** [comment]
Hi @MyraBaba,
thank you for adding the requested details! 
I have added an extended_entities to the Tweet entity a few days ago -- have a look at https://github.com/DanielaSfregola/twitter4s/commit/ef1fad8f1537f420b750348b4a424bc2691686b5#diff-e137776e4702245e95d2d6cbaadabd2dR12

The code is not released yet, so you need to use 4.2-SNAPSHOT in order to see it.

**Comment by MyraBaba** [comment]
where can I get snapshots  sources also ?

**Comment by DanielaSfregola** [comment]
In the README you have all the information on how to use SNAPSHOT versions -- see https://github.com/DanielaSfregola/twitter4s#snapshot-versions.

In summary, you need to:
1) Assuming you are using sbt, you need to add the resolver for snapshot to your program (either on build.sbt or plugins.sbt): 
```scala
resolvers += Resolver.sonatypeRepo("snapshots")
```

2) update your version to "4.2-SNAPSHOT"

**Comment by MyraBaba** [comment]
Hi,

I added snapshot 4.2 .  When I checked the TwitterSearchClient:
`def searchTweet(query: String,
                  count: Int = 15,
                  include_entities: Boolean = true,
                  result_type: ResultType = ResultType.Mixed,
                  geocode: Option[GeoCode] = None,
                  language: Option[Language] = None,
                  locale: Option[String] = None,
                  until: Option[LocalDate] = None,
                  since_id: Option[Long] = None,
                  max_id: Option[Long] = None,
                  callback: Option[String] = None): Future[StatusSearch] = {
    val parameters = TweetSearchParameters(query.escapeSpecialChars, count, include_entities, result_type, geocode, language, locale, until, since_id, max_id, callback)
    Get(s"$searchUrl/tweets.json", parameters).respondAs[StatusSearch]
  }`

there should be tweet_mode  parameter  to get extended_entities. 

`                  tweet_mode: Option[String] = None
`
so we can put tweet_mode = extended   parameter.
did I  missed something ?

**Comment by DanielaSfregola** [comment]
Hi @MyraBaba,
we do not support this parameter at the moment. I have created a ticket to add it -- see #102.

**Comment by MyraBaba** [comment]
Hi Daniela,

I am also trying to help and also contribute.  Not expert in the Scala but yet.

Meanwhile for my debugging how can I get the raw json reponse from the twitter in the search client ? It could be helpfull for debugging to understand why something is not working.

If I miss configured the Entities such as ,  its not giving any error to poing me direction. 

To put an optionto get RAW twitter esponse could be a plus.  May be there is a way already but i couldn’t figure it out.

thx

**Comment by DanielaSfregola** [comment]
Hi @MyraBaba,
I think if you use the debugger, you should be able to see the whole response coming from Twitter.

Regards,
Daniela

**Comment by MyraBaba** [comment]
strugling with intellij..  because of the futures I think intellij missing some point..

working..on it

**Comment by MyraBaba** [comment]
Hi Daniela,

I have a quick fix for the tweet_mode=extended..

when extended json requested there is few changes:

> "statuses": [
    {
      "created_at": "Sat Jan 28 00:52:05 +0000 2017",
      "id": 825144379857829889,
      "id_str": "825144379857829889",
      "full_text": "RT @baydemirosman: AKP'nin Referandum çalışması.\nMilletvekilleri gözaltında. https://t.co/s553rzCjat",
      "truncated": false,
      "display_text_range": [......

full_text  and display_text_range  field added .  no more text  field.

so:

in the entities.Tweet.scala:
` text: Option[String],
   full_text: Option[String],
   display_text_range: Seq[Int],`

is worked for me..

FYI...

I assume there is a parameter already in TwititerSearchClient.scala "tweet_mode"

**Comment by DanielaSfregola** [comment]
Hi @MyraBaba ,
Please  do not add the code to the ticket, but create a pull request. Also, please comment in the correct ticket: this ticket is not about tweet mode (see #102), but it about adding extended entities to a tweet and it is already been closed.
