### ISSUE TITLE
Support for tweet_mode

### ISSUE THREAD

**Issue by DanielaSfregola** [DanielaSfregola/twitter4s#102]
tweet_mode is a parameter that has been added to all the REST endpoint -- see https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

We should support it (feature request from #101 ).

**Comment by MyraBaba** [comment]
Hi,

I added tweet_mode to TwitterSearchClient:

`def searchTweet(query: String,
                  count: Int = 15,
                  include_entities: Boolean = true,
                  result_type: ResultType = ResultType.Mixed,
                  geocode: Option[GeoCode] = None,
                  language: Option[Language] = None,
                  tweet_mode: Option[String] = None,
                  locale: Option[String] = None,
                  until: Option[LocalDate] = None,
                  since_id: Option[Long] = None,
                  max_id: Option[Long] = None,
                  callback: Option[String] = None): Future[StatusSearch] = {
    val parameters = TweetSearchParameters(query.escapeSpecialChars, count, include_entities,result_type, geocode, language, tweet_mode , locale, until, since_id, max_id, callback)
    Get(s"$searchUrl/tweets.json", parameters).respondAs[StatusSearch]
  }
}
`

when I use like this 👍 
`client.searchTweet(query, count = 100, result_type = ResultType.Recent, tweet_mode = Option("extended"),max_id = max_id  ,language = Option(Language.Turkish)).flatMap { result => . . . .....`
 
zero tweets saved in the search demo.  

without twee_mode  parameter its working and also extracting the extended_entities if its present.

FYI

**Comment by smrnv** [comment]
Hi @DanielaSfregola , in the new response there are some new fields in the Tweet object if we search with ```tweet_mode=extended``` param. Here they are: ```full_text``` and ```display_text_range```. But there is no ```text``` field. Should I create a custom mapper and place ```full_text``` value in the ```text``` for backward compatibility?

**Comment by DanielaSfregola** [comment]
Hi @smrnv, I think it is a great idea - I was expecting `tweet_mode=extended` to just return the `text` field with the whole text in it. 

What kind of information is included in `display_text_range`? I am wondering if we should add `full_text` and `display_text_range` to our Tweet case class for completeness even if we replace the content of `text`. Note that adding fields is not a breaking change, so we can do it in the next release

**Comment by smrnv** [comment]
I suppose ```display_text_range``` contains info about ```full_text```. It looks like 
```json 
"display_text_range": [0, 231]
```
I think normally first value is always 0 and the last one is the last number of text symbol, so it represents a tweet text length.

**Comment by smrnv** [comment]
My suggestion is: ```case class Tweet``` can become a trait with the same fields as it now and there will be two case classes with Tweet mixin:  ```ExtendedTweet extends Tweet``` for the extended mode and ```ClassicalTweet extends Tweet``` for the usual mode. So ```TwitterSearchClient.searchTweet``` will return a ```trait Tweet```. I don't think that many of users use current Tweet case class in pattern matching, and it will not a big problem, but if so - the just should use ClassicalTweet instead. And if you need some specific fields from the extended response - just case match result on the ExtendedTweet

**Comment by DanielaSfregola** [comment]
I think we do not need a sum type here - plus it would be a major breaking change. We can simply have the following:
```
case class Tweet(
text: String,
full_text: Option[String],
display_text_range: Option[Seq[Int]]
)
```

....and document that full_text and display_text_range fields are there only for expanded tweets - which I believe is consistent with the twitter docs.
