### ISSUE TITLE
Incorrect request being sent to twitter for TwitterStreamingClient.filterStatuses

### ISSUE THREAD

**Issue by chrisbeach** [DanielaSfregola/twitter4s#120]
I'm finding `TwitterStreamingClient.filterStatuses` method is generating an invalid request to Twitter:
I'm supplying Seqs of Longs and Strings as required (the code compiles)

However, the request is rejected by Twitter because it appears to contain a dodgy toString on Scala objects - resulting in "Vector(..." etc

`follow=Vector%28731067654220419072%2C+751909641274155008%29&language=en&stall_warnings=true&track=Vector%28se23%29`

**Comment by DanielaSfregola** [comment]
Oh Dear! Thanks for raising this -- I'll solve it with high priority!

**Comment by DanielaSfregola** [comment]
This is now available in twitter4s 5.0
