### ISSUE TITLE
Clarify TwitterStatusClient scaladoc

### ISSUE THREAD

**Issue by RPCMoritz** [DanielaSfregola/twitter4s#130]
The current documentation reads:
`@param tracks : Empty by default. Keywords to track. Phrases of keywords are specified by a comma-separated list.
`
Yet, the actual implementation expects a Seq[String]. This leaves unclear, whether a single-element Seq[String] with a comma-separated String is expected, or whether documentation is wrong, and a Seq of Strings with one term/id per String is expected.

The other, non-String parameters make this clear, but the API-doc is still misleading - the passed argument is never "comma-separated" - that doesn't happen until the .toString much later.

**Comment by DanielaSfregola** [comment]
Hi @RPCMoritz,
thanks for the heads up! You are absolutely right, we'll improve the documentation asap.

(PRs are always welcome!)

Regards,
Daniela
