### ISSUE TITLE
280 chars support

### ISSUE THREAD

**Issue by DanielaSfregola** [DanielaSfregola/twitter4s#135]
Now that tweets can have up to 280 chars, we really need to update the library!

Not sure what changed in the API yet, finding that out could be a good first step.

**Comment by ivanopagano** [comment]
Does the code explicitly use the limit somewhere? How would it affect the client?

**Comment by DanielaSfregola** [comment]
We do not limit the length when creating a tweet but we rely on Twitter to block us if the length is not quite right (see [here](https://github.com/DanielaSfregola/twitter4s/blob/master/src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/statuses/TwitterStatusClient.scala#L338) for the code)....so that should be already be working (obviously, documentation should be updated and this assumption should be tested.

I guess the problem would be when retrieving tweets as I am not sure if the API is changed at all when "long tweets" are involved. Maybe #102 is all we have to do? not sure as I haven't had time to check the documentation yet.

**Comment by raam86** [comment]
* Like you suspected the tweets are getting truncated:

```
object LongTweets  extends App{
  import com.danielasfregola.twitter4s.TwitterRestClient
  import scala.concurrent.duration._
  val restClient = TwitterRestClient()
  val ft = restClient.getTweet(912927410689052672L)
  val t = Await.result(ft, 10 seconds)
  println(t.data.text)
  println(t.data.text.length)
  assert(t.data.text.length == 280)
}
Hello world, this is a large Tweet. This tweet has 280 characters instead of the regular and boring 140, and it's g… https://t.co/nWG6hggkyS
140
Exception in thread "main" java.lang.AssertionError: assertion failed
```

Seems like twitter are still rolling this feature out and there's not documentation on how to get the full tweet, the `truncated` property is set to true, something that shouldn't happen to "new" tweets. 

I guess we'll have to wait for twitter to release more details. 
* The extended  tweet page return 404

**Comment by DanielaSfregola** [comment]
Awesome, thanks @raam86 for looking into this!

**Comment by raam86** [comment]
It's a was pleasure reading your docs and code so thank you :1st_place_medal:
