### ISSUE TITLE
Giter8 template

### ISSUE THREAD

**Issue by DanielaSfregola** [DanielaSfregola/twitter4s#137]
...giter8 is cool! Can we create a template for a skeleton project using twitter4s?

**Comment by bsamaripa** [comment]
Hi @DanielaSfregola, I'll take take this one. Since it would require a new github repo to be created, how should ownership be handled? I wouldn't mind transferring ownership once the initial version is complete.

**Comment by DanielaSfregola** [comment]
Hi @bsamaripa, thanks for helping out!

I have just created a new repo for the giter8 twitter4s template: have a look at https://github.com/DanielaSfregola/twitter4s.g8

Cheers,
D.

**Comment by DanielaSfregola** [comment]
I have created the base of the template and setup travis. The only bit that is now actually missing is writing the actual twitter4s code.
