### ISSUE TITLE
Actor system termination question

### ISSUE THREAD

**Issue by vooolll** [DanielaSfregola/twitter4s#140]
Hi, Inspired by twitter4s, I start building client library for facebook - https://github.com/vooolll/facebook4s. Could you please answer, should I shutdown actor system on each request to client library? How it works in `twitter4s`? I guess creation of actor system consumes resources, how you approach this?

**Comment by DanielaSfregola** [comment]
Hi @vooolll,
I am honored twitter4s expired your project!

In my first implementation, I was using the same actor system for all the requests. This was ok, but it was exposing details to the API that people were struggling with.

At present, I spin up an actor system, make the request and shutdown the system (see [here](https://github.com/DanielaSfregola/twitter4s/blob/5759a40d631c1c47a6ab70b772f522f3396a042b/src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/RestClient.scala#L21) for some example code). This has the advantage of making the API super easy and agnostic from the actual implementation

**Comment by DanielaSfregola** [comment]
Issue #103 is a good reason to spin up an actor system every time: if not, the consumer of your API will have the responsibility of killing the actor system.

**Comment by vooolll** [comment]
@DanielaSfregola Thank you. Seems like I look into right place.
