### ISSUE TITLE
Left over spray configuration

### ISSUE THREAD

**Issue by DanielaSfregola** [DanielaSfregola/twitter4s#146]
https://github.com/DanielaSfregola/twitter4s/blob/master/src/main/resources/reference.conf

....why do we have a spray configuration there?

**Comment by mfirry** [comment]
Can I just remove it?

**Comment by DanielaSfregola** [comment]
yes, it is not used anymore -- it's a leftover of the first version of twitter4s that was initially implemented in spray :)
