### ISSUE TITLE
Update links for Twitter docs

### ISSUE THREAD

**Issue by DanielaSfregola** [DanielaSfregola/twitter4s#149]
I have just discovered that Twitter has changed most of the links for its documentation. 

We should double-check that the links in the twitter4s scaladoc are still pointing to the right pages.

**Comment by DanielaSfregola** [comment]
List of all REST Clients docs:
- [ ] [TwitterAccountClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/account/TwitterAccountClient)
- [ ] [TwitterApplicationClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/application/TwitterApplicationClient)
- [ ] [TwitterBlockClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/blocks/TwitterBlockClient)
- [ ] [TwitterDirectMessageClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/directmessages/TwitterDirectMessageClient)
- [ ] [TwitterFavoriteClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/favorites/TwitterFavoriteClient)
- [ ] [TwitterFollowerClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/followers/TwitterFollowerClient)
- [ ] [TwitterFriendClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/friends/TwitterFriendClient)
- [ ] [TwitterFriendshipClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/friendships/TwitterFriendshipClient)
- [ ] [TwitterGeoClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/geo/TwitterGeoClient)
- [ ] [TwitterHelpClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/help/TwitterHelpClient)
- [ ] [TwitterListClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/lists/TwitterListClient)
- [ ] [TwitterMuteClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/mutes/TwitterMuteClient)
- [ ] [TwitterSavedSearchClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/savedsearches/TwitterSavedSearchClient)
- [ ] [TwitterSearchClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/search/TwitterSearchClient)
- [ ] [TwitterStatusClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/statuses/TwitterStatusClient)
- [ ] [TwitterSuggestionClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/suggestions/TwitterSuggestionClient)
- [ ] [TwitterUserClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/users/TwitterUserClient)
- [ ] [TwitterTrendClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/trends/TwitterTrendClient)
- [ ] [TwitterMediaClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/media/TwitterMediaClient)

List of all the Streaming Clients docs:
- [ ] [TwitterStatusClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClient.html)
- [ ] [TwitterSiteClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/streaming/sites/TwitterSiteClient.html)
- [ ] [TwitterUserClient](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/streaming/users/TwitterUserClient.html)

**Comment by lapmid** [comment]
what i have to do in this issue exactly ?? actually newbie at open source contribution please explain

**Comment by sammyrulez** [comment]
working on blocks and directmessages

**Comment by DanielaSfregola** [comment]
Hi @lapmid, welcome to the magic world of opensource!

Let's take for example TwitterMuteClient: his scaladoc is [here](http://danielasfregola.github.io/twitter4s/5.1/api/com/danielasfregola/twitter4s/http/clients/rest/mutes/TwitterMuteClient), its code is [here](https://github.com/DanielaSfregola/twitter4s/blob/master/src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/mutes/TwitterMuteClient.scala).

Fork the repo and fix the links in the file that are broken. Once you are done, open a PR so that I can accept your change....and happy days! 💃 

I hope it helps!
 
Cheers,
D.

**Comment by Ocete** [comment]
Starting to work on account client and application client

**Comment by sammyrulez** [comment]
working on TwitterFavoriteClient and TwitterFollowerClient

**Comment by Ocete** [comment]
Actually I just updated TwitterMuteClient

**Comment by lapmid** [comment]
I have fixed links to TwitterAccountClient what should i do next

**Comment by lapmid** [comment]
@DanielaSfregola Should I make commit Or PR for those files also which have all links working already

**Comment by DanielaSfregola** [comment]
@lapmid is the links are already working, just put a comment in this issue saying that you reviewed the file and that all its links are already correct -- I'll mark it as done

**Comment by lapmid** [comment]
Okay

**Comment by DanielaSfregola** [comment]
All links have been updated! Thanks guys for your help!
