### ISSUE TITLE
Issues encoding operators in GET search

### ISSUE THREAD

**Issue by Koalk** [DanielaSfregola/twitter4s#174]
Hi, appreciate the library you've built here. Has help me a lot.

I was trying to execute a search for tweets mentioning an url (using the "url:" operator in the query) but it seems like the encoding goes wrong at some point:
Query string I pass to the library: "url:https://github.com/ReactiveX/RxJava"
Query comming back in the search metadata: "url%253Ahttps%253A%252F%252Fgithub.com%252FReactiveX%252FRxJava"
The actual url utf-8 encoding should actually be: "url%3Ahttps%3A%2F%2Fgithub.com%2FReactiveX%2FRxJava"

I've tried encoding it myself but still some stuff gets added to the mix and I get the same thing at the end.

**Comment by DanielaSfregola** [comment]
Fix released in twitter4s 5.5
