### ISSUE TITLE
Replace `java.util.Date` with `java.time.Instant`

### ISSUE THREAD

**Issue by vooolll** [DanielaSfregola/twitter4s#177]
According to https://docs.oracle.com/javase/tutorial/datetime/iso/legacy.html, it is better to use `Instant` instead of `java.util.Date`.

**Comment by DanielaSfregola** [comment]
Hi @vooolll,
thanks for your suggestion. Could you please elaborate on why `Instant` should be better than `Date`?

I had a very quick look at the link you posted and they explicitly say they are equivalent, but from my point of view `Date` is more human-friendly than `Instant`.

That being said, I am happy to listen to your arguments on why we should have a breaking change in our API in favor of `Instant` :)

**Comment by DanielaSfregola** [comment]
Had another look at the article and you might be right: they suggest to use `java.time` package rather than `java.util`. 

However, I have concerns about JDK7: if we make this breaking, I am afraid we will need to drop the support for JDK7.

WDYT?

**Comment by vooolll** [comment]
As I saw you don't build it against jdk7 on travis, but if keeping jdk7 support is important then no need to change it `Date` to `Instant`.

**Comment by vooolll** [comment]
Probably you need to build `twitter4s` with both jdk7, jdk8, to see incompatibility problems

**Comment by DanielaSfregola** [comment]
I have updated travis to build on JDK 7.

Unfortunately, I am afraid we need to reject this suggestion as we do not want to drop support for JDK 7 -- at least not for now!

Cheers and thanks for the constructive discussion!
D.

**Comment by DanielaSfregola** [comment]
Reopening as we are going to drop JDK 7 in the next major release. A good excuse to probably change the date type here!
