### ISSUE TITLE
New Direct Message API announcement - actions to take?

### ISSUE THREAD

**Issue by DanielaSfregola** [DanielaSfregola/twitter4s#194]
.....is this something we should take action on?

https://twittercommunity.com/t/new-direct-message-api-features-now-available-to-all/98733

If so, create issues accordingly. 

NOTE: this ticket is just about investigating if and what we have to do, not the actual implementation.

**Comment by borsik** [comment]
https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/guides/direct-message-migration.html

**Comment by DanielaSfregola** [comment]
New endpoint added - a part for new endpoint to delete messages -- for which I am going to create a new ticket.

Closing this one
