### ISSUE TITLE
KillerSwitch returned before failure and error handling

### ISSUE THREAD

**Issue by bignacio** [DanielaSfregola/twitter4s#197]
Hello,

I'm trying to implement a backoff/reconnect when calling `filterStatuses` but I'm having trouble finding the right place for the error handling code.

I found the future returned by `filterStatuses` not always contains a `Failure` (in `onComplete`) even though a 420 has been thrown.
But sometimes it does. 

Thanks

**Comment by DanielaSfregola** [comment]
Hi @bignacio,
unfortunately, this is not currently supported by twitter4s but it has been in our backlog for a while.

Similar issue (but not quite the same): https://github.com/DanielaSfregola/twitter4s/issues/142

I'll add it to the roadmap, as this seems like an important issue to solve -- unfortunately, it involves quite a bit of redesigning of how streaming works.

In the meanwhile, feel free to give it a try -- PRs are always welcome.

Cheers,
Daniela

**Comment by DanielaSfregola** [comment]
[Note]

This may actually just be a bug, probably caused by https://github.com/DanielaSfregola/twitter4s/blob/master/src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/StreamingClient.scala#L45

It may be easier to fix by either increasing the timeout (maybe make it configurable) or by simply find a better way of doing this!

**Comment by DanielaSfregola** [comment]
Hi @bignacio,
I have published a fix for the issue related to the killSwitch returning too soon on twitter4s 5.5-SNAPSHOT -- soon (less than a week?) to be twitter4s 5.5.

For the issue related to the inability to properly do error handling, please keep an eye on #142 -- hopefully we will add this functionality soon!

Cheers,
Daniela

**Comment by bignacio** [comment]
Fantastic, thank you Daniela!

**Comment by DanielaSfregola** [comment]
Released in twitter4s 5.5 -- now ready for you in maven central!
