### ISSUE TITLE
Update json4s

### ISSUE THREAD

**Issue by wzorgdrager** [DanielaSfregola/twitter4s#223]
Your current version runs on json4s version `3.5.3` (see [here](https://github.com/DanielaSfregola/twitter4s/blob/dc3e35c67dbf3cbe2010336af48d1df319e4dc43/build.sbt#L21)) json4s is already on version [`3.6.0-M4`](https://mvnrepository.com/artifact/org.json4s/json4s-core_2.12/3.6.0-M4). It gives me conflicts when I both use twitter4s and json4s as dependency in my project. Maybe json4s can be updated if it doesn't give any conflicts with the project?

**Comment by DanielaSfregola** [comment]
Hi @wzorgdrager, 
I am not sure if an `-M*` version (which I believe stands for `milestone`) is stable enough for us to upgrade the library. 

I believe the current latest stable version of json4s is 3.5.4 (published in May 2018).

**Comment by wzorgdrager** [comment]
You're right. We will downgrade our version to a stable one.
