### ISSUE TITLE
Release v6.0

### ISSUE THREAD

**Issue by rtyley** [DanielaSfregola/twitter4s#238]
Could you release v6.0? PR #220 merged the 6.0 branch into master in April 2018, and I [hear](https://github.com/DanielaSfregola/twitter4s/issues/237#issuecomment-465447462) people have been asking for it!

![image](https://user-images.githubusercontent.com/52038/54448205-127be080-4743-11e9-869e-4f544bda574c.png)

_(my particular interest in 6.0 is f6f174ec2, providing `tweet_mode` for `tweetLookupMapped`)_

**Comment by DanielaSfregola** [comment]
You are absolutely right - I have been delaying this release for too long! 
Let me do it right now. I'll update this issue once the release is complete.

**Comment by DanielaSfregola** [comment]
Hi @rtyley,
the release for 6.0 has been completed (twitter announcement coming in the next few minutes)! I have published to sonatype and it should be synced to maven central soon.

Thanks for your patience and for the polite reminder! ;)
Daniela

**Comment by DanielaSfregola** [comment]
(waiting for the release to be in maven central before closing...)

**Comment by DanielaSfregola** [comment]
YEAHHH! It's now in maven central -- closing
