### ISSUE TITLE
Release with major bump to 7.0?

### ISSUE THREAD

**Issue by zzvara** [DanielaSfregola/twitter4s#323]
@DanielaSfregola  With the new AKKA version upgrade, I think it would be best to bump to 7.0, to warn users that things will definitely break upon `twitter4s` upgrade.

**Comment by DanielaSfregola** [comment]
HI @zzvara, I have a few PRs that change the API so a major jump in version is in the plans.
Hopefully, I'll get to the release today :)

**Comment by DanielaSfregola** [comment]
version 7.0 is on its way to maven central! 

Closing this issue 👍
