### ISSUE TITLE
Cannot find value "Language"

### ISSUE THREAD

**Issue by Wajktor** [DanielaSfregola/twitter4s#342]
Cannot find value "Language" when using twitterSearch

**Comment by DanielaSfregola** [comment]
Hi @Wajktor,

could you please elaborate on what you mean by `cannot find value "Language"`? Is it a runtime error? do you have a stack trace?

Thanks,
Daniela

**Comment by DanielaSfregola** [comment]
Closing, not enough information to start the investigation
