### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by DanielaSfregola** [DanielaSfregola/twitter4s#42]
At present, we only support application authentication.
We should also support user authentication. See https://dev.twitter.com/oauth/overview/introduction

**Comment by gderham** [comment]
I'll do this.

**Comment by DanielaSfregola** [comment]
https://dev.twitter.com/oauth/reference

**Comment by DanielaSfregola** [comment]
https://oauth.net/core/1.0/#anchor9
