### ISSUE TITLE
Publishing release 7.1 to Maven Central

### ISSUE THREAD

**Issue by rtyley** [DanielaSfregola/twitter4s#465]
Hi there! I see `twitter4s` [v7.1](https://github.com/DanielaSfregola/twitter4s/releases/tag/v7.1) was tagged in February 2021, but it [doesn't seem to be on Maven Central](https://repo1.maven.org/maven2/com/danielasfregola/twitter4s_2.13/) - would you be able to do a release?

The 7.1 release is helpful to us at the Guardian, as we're updating our `json4s` version, which conflicts with the old version currently in `twitter4s` v7.0.

Possibly related, tho' not a blocker for us: https://github.com/DanielaSfregola/twitter4s/issues/332

**Comment by DanielaSfregola** [comment]
Hi Robert,
I'll try to do a release this weekend.

Cheers,
Daniela

**Comment by rtyley** [comment]
Many thanks Daniela - our Scala learning group at work is still loving your book by the way!

**Comment by DanielaSfregola** [comment]
Thanks for your kind words! I am glad your learning group is enjoying my book :)

So I have published both v7.1 and v8.0 (see tags). Let me know if after a day you still do not see them on maven central! (these things can be tricky at times!)

Cheers,
Daniela

**Comment by rtyley** [comment]
Thanks so much Daniela! I can confirm that the new releases are [available in Maven Central](https://repo1.maven.org/maven2/com/danielasfregola/twitter4s_2.13/) - thank you!

![image](https://user-images.githubusercontent.com/52038/169997154-f5147573-dd93-4cc8-9fb9-1e0c055f0964.png)
