### ISSUE TITLE
Response parser error `No usable value for created_at`

### ISSUE THREAD

**Issue by skibi** [DanielaSfregola/twitter4s#5]
Hi
When i run tests i got error messages similar to that in demo issue

https://github.com/DanielaSfregola/twitter4s-demo/issues/1

When i go deeper i saw that have same problem even for such simple code
```
val formater = new SimpleDateFormat("EEE MMM dd HH:mm:ss ZZZZ yyyy")
val date = formater.parse("Mon Dec 08 20:00:20 +0000 2014")
```
```
Exception in thread "main" java.text.ParseException: Unparseable date: "Mon Dec 08 20:00:20 +0000 2014"
	at java.text.DateFormat.parse(DateFormat.java:366)
```

But that works fine
```
val formater = new SimpleDateFormat("EEE MMM dd HH:mm:ss ZZZZ yyyy", Locale.US)
val date = formater.parse("Mon Dec 08 20:00:20 +0000 2014")
```

Im from Poland so when default `Locale` are used they are set as `PL`

I thing problem is here https://github.com/DanielaSfregola/twitter4s/blob/b5357ffc9a2ca026bb9eb2abfbfd692ba607ce46/src/main/scala/com/danielasfregola/twitter4s/http/unmarshalling/JsonSupport.scala#L16 
here are used default `Locale` ( for me `Locale.PL` )

TEMPORARY (and only temporary) solution is set proper `Locale` 
```
Locale.setDefault(Locale.US)
```

**Comment by DanielaSfregola** [comment]
Thank you for raising this issue! I am going to fix it asap.

The issue seems to be related to `SimpleDateFormat` that has a dependency on `Locale` ...and obviously this doesn't work in you have a different default Locale!  

See http://stackoverflow.com/questions/4521715/twitter-date-unparseable for more details.
