### ISSUE TITLE
Migration to Akka-Http

### ISSUE THREAD

**Issue by DanielaSfregola** [DanielaSfregola/twitter4s#55]
We currently using Spray -- that is no longer supported by the Akka team.
We should migrate to Akka-Http.

**Comment by qabbasi** [comment]
Hi Daniela,

I will work on this issue and will hopefully come up with pr around...

Cheers,
Qaiser

**Comment by DanielaSfregola** [comment]
starting working on this as well, as it has become the highest priority...
