### ISSUE TITLE
Introduce JSON marshalling with io.circe

### ISSUE THREAD

**Issue by qabbasi** [DanielaSfregola/twitter4s#63]

**Comment by DanielaSfregola** [comment]
Although this is not a priority at the moment, I think using circe to serialize/deserialize would be a good idea! 👍

**Comment by DanielaSfregola** [comment]
After speaking with quite a few people, Circe is a bit slow at compilation time.

For now, let's try not to depend on libraries that are particularly heavy on the compilator -- we want this project to be quick at compile time for interactive notebooks like Jupiter.

We are not going to this. At least, for the moment.
