### ISSUE TITLE
Support all standard params for Streaming requests

### ISSUE THREAD

**Issue by DanielaSfregola** [DanielaSfregola/twitter4s#71]
See https://dev.twitter.com/streaming/overview/request-parameters 
There are some parameters in the streaming API that we do not support....we should!

**Comment by mfirry** [comment]
- [ ] delimited
- [ ] stall_warnings
- [ ] filter_level
- [ ] language
- [ ] follow
- [ ] track
- [ ] locations
- [ ] count
- [ ] with
- [ ] replies
- [ ] stringify_friend_id

**Comment by allantl** [comment]
Hi @mfirry, are you working on this issue?
If not, I can take this one.

**Comment by DanielaSfregola** [comment]
Note on `delimited` is used internally to consume the stream, probably I wouldn't expose it in our API. Feel free to disagree and to convince me otherwise! 👍

**Comment by mfirry** [comment]
@allantl go ahead.
