### ISSUE TITLE
Stream can not be received in a few minutes

### ISSUE THREAD

**Issue by kamijin-fanta** [DanielaSfregola/twitter4s#82]
When the stream stops, no error is displayed.
How can I improve the fault tolerance of my application?

example codes

```scala
// main.scala
import com.danielasfregola.twitter4s.entities.enums.Language
import com.danielasfregola.twitter4s.{TwitterStreamingClient}
import com.danielasfregola.twitter4s.entities.{Tweet}
object main {
  def main(args: Array[String]): Unit = {
    val streamingClient = TwitterStreamingClient()
    streamingClient.sampleStatuses(Seq(Language.Japanese)) {
      case tweet: Tweet => println(tweet.text)
      case other => println(other)
    }

    println("Pooling...")
    if (io.StdIn.readLine != null) {
      println("Shutdown")
      streamingClient.system.terminate()
    }
  }
}
```

```sbt
// build.sbt

scalaVersion := "2.11.8"

resolvers += Resolver.sonatypeRepo("releases")

libraryDependencies ++= {
  val akkaVersion = "2.4.16"
  Seq(
    "com.typesafe.akka" %% "akka-actor" % akkaVersion,
    "com.danielasfregola" %% "twitter4s" % "4.0"
  )
}

fork in run := true
connectInput in run := true
```

**Comment by DanielaSfregola** [comment]
Hi @kamijin-fanta,
by definition a stream never stops, so I am not sure what is the desired behaviour here :)

Note that in the backlog we have a ticket (see #68 ) about adding the functionality of closing the stream from the client if needed -- although at the moment this functionality is not supported.

Cheers,
D.

**Comment by kamijin-fanta** [comment]
@DanielaSfregola Thank!

To quickly reproduce this error, disconnect the LAN cable.
I think that it will be the same situation as my own environment.

If handling of errors is possible, I can restart AkkaStream, but in the current situation it is difficult.

**Comment by DanielaSfregola** [comment]
Hi @kamijin-fanta,
what about something like the following?

```scala 
import akka.actor.ActorSystem
import com.danielasfregola.twitter4s.entities.enums.Language
import com.danielasfregola.twitter4s.entities.Tweet

import scala.concurrent.ExecutionContext.Implicits.global
import scala.util.{Failure, Success}

object Main extends App {
  
  implicit val system = ActorSystem()

  val streamingClient = TwitterStreamingClient()
  
  val result = streamingClient.sampleStatuses(Seq(Language.Japanese)) {
    case tweet: Tweet => println(tweet.text)
  }
  
  result.onComplete {
    case Success(_) => println("Success!")
    case Failure(ex) =>
      println(s"Failure :(  -- $ex")
      system.terminate()
  }
}
```

The idea is that when in general when a stream is completed it will return a `Future[Unit]`. That future contains information on the connection of the stream, so in your case it will contain that the stream failed because of network issues.

**Comment by kamijin-fanta** [comment]
I was not aware that the Future was being returned.
Thank you!

But, such an error has occurred.

```
[info] Failure :(  -- EntityStreamSizeException: actual entity size (None) exceeded content length limit (1000 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream.
```

When you write the setting, you can check it immediately.

```hocon
akka.http {
  client {
    parsing {
      max-content-length = 1000
    }
  }
}
```

I think there is a structural problem...

**Comment by kamijin-fanta** [comment]
Change the setting, the error no longer occurs.

```
akka.http {
  client {
    parsing {
      max-content-length = 5g
    }
  }
}
```
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
27700 ubuntu    20   0 3478960 297056  14768 S   2.0  7.3  13:21.18 java
```

**Comment by DanielaSfregola** [comment]
My fault! I forgot to specify that that particular stream is potentially infinite.

I am going to fix it and release a patch version for it.

**Comment by DanielaSfregola** [comment]
A fix for this has been released in version 4.0.1 -- it is on sonatype already, it will be in maven central in a couple of hours.

Closing this ticket. If this is still not working, please reopen the ticket.

**Comment by aron-bordin** [comment]
My stream is stopping after a few minutes. I edited https://github.com/DanielaSfregola/twitter4s/blob/master/src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/ErrorHandler.scala#L5 to display the error, and I'm getting:

> akka.http.scaladsl.model.EntityStreamException: Entity stream truncation

do you know what is wrong?

**Comment by DanielaSfregola** [comment]
@aron-bordin could you please open a new issue? Also, it would be great if you could include a representative fragment of your code.
