### ISSUE TITLE
entities.media always empty.

### ISSUE THREAD

**Issue by MyraBaba** [DanielaSfregola/twitter4s#96]
entities.media  and urls always empty in Tweet4s-demo   search rest point.

fyi

**Comment by MyraBaba** [comment]
have you chance to investigate it ? any clue *

**Comment by DanielaSfregola** [comment]
Hi @MyraBaba, unfortunately, I still have to find the time to look at this -- but it is next in my TODO list.

In the meanwhile, feel free to have a look at the code and propose a fix - PRs are always welcome!

**Comment by MyraBaba** [comment]
I am looking.. my scala knowledge is pro-mid level.  so didnt discover yet.

I have a small integration for demo code to wirte elastic search.  if I can find out how to submit ( :  )  )  I will do it.

PS: is there any way to get RAW json response . can you direct me ?


thx

**Comment by DanielaSfregola** [comment]
we do have several RAW json that we use in our tests. See for example: https://github.com/DanielaSfregola/twitter4s/blob/master/src/test/resources/twitter/rest/statuses/retweet.json

The error is probably in the way we convert the json received by twitter into the Tweet case class.

**Comment by MyraBaba** [comment]
I mean the RAW json in the code at first received. to tract conversion.

**Comment by DanielaSfregola** [comment]
See https://github.com/DanielaSfregola/twitter4s/blob/master/src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/RestClient.scala#L30

`json4sUnmarshaller` is the function that converts the body of the response into the case class

**Comment by MyraBaba** [comment]
I try to track json response : in RestClient.scala :


def respondAs[T: Manifest]: Future[T] =
  for {
    requestWithAuth <- withOAuthHeader(request)
    t <- sendReceiveAs[T](requestWithAuth)
  } yield t

I debug t   .  And look in it. All entities.media is also empty . is it before conversion or after ?

**Comment by DanielaSfregola** [comment]
Bug Found! PR coming soon

**Comment by DanielaSfregola** [comment]
Hi @MyraBaba, the fix is now in 4.2-SNAPSHOT.
It will be released as part of 4.2.

Cheers,
Daniela

**Comment by MyraBaba** [comment]
I just discovered the solution :)  in the : https://github.com/DanielaSfregola/twitter4s/blob/master/src/main/scala/com/danielasfregola/twitter4s/entities/Entities.scala

I added : 

`case class EntitiesMediaDetails(display_url: String ,
                                expanded_url: String ,
                                id_str: String ,
                                media_url: String ,
                                url: String)`

Than entities.media  looks start to delivering .

Only one question :  there is a field :  entites.media.type ..  I coulndt adress the type in jason to the case class.

when I try : type: String   it refers someting alse you already used.

FYI

**Comment by MyraBaba** [comment]
Hi,

Where can I find 4.2-SNAPSHOT ?  couldnt find the jar.  or sbt def.

**Comment by DanielaSfregola** [comment]
Please refer to the README: https://github.com/DanielaSfregola/twitter4s#snapshot-versions
